source_group(Math           REGULAR_EXPRESSION "(include/Pomdog|src)/Math/*")
source_group(Math\\Detail   REGULAR_EXPRESSION "(include/Pomdog|src)/Math/Detail/*")

target_sources(pomdog_static PRIVATE
    # NOTE: Math
    ${POMDOG_INC_DIR}/Math/BoundingBox.hpp
    ${POMDOG_SRC_DIR}/Math/BoundingBox.cpp
    ${POMDOG_INC_DIR}/Math/BoundingBox2D.hpp
    ${POMDOG_SRC_DIR}/Math/BoundingBox2D.cpp
    ${POMDOG_INC_DIR}/Math/BoundingCircle.hpp
    ${POMDOG_SRC_DIR}/Math/BoundingCircle.cpp
    ${POMDOG_INC_DIR}/Math/BoundingFrustum.hpp
    ${POMDOG_SRC_DIR}/Math/BoundingFrustum.cpp
    ${POMDOG_INC_DIR}/Math/BoundingSphere.hpp
    ${POMDOG_SRC_DIR}/Math/BoundingSphere.cpp
    ${POMDOG_INC_DIR}/Math/Color.hpp
    ${POMDOG_SRC_DIR}/Math/Color.cpp
    ${POMDOG_INC_DIR}/Math/ContainmentType.hpp
    ${POMDOG_INC_DIR}/Math/Degree.hpp
    ${POMDOG_INC_DIR}/Math/ForwardDeclarations.hpp
    ${POMDOG_INC_DIR}/Math/Math.hpp
    ${POMDOG_SRC_DIR}/Math/Math.cpp
    ${POMDOG_INC_DIR}/Math/Matrix2x2.hpp
    ${POMDOG_INC_DIR}/Math/Matrix3x2.hpp
    ${POMDOG_INC_DIR}/Math/Matrix3x3.hpp
    ${POMDOG_INC_DIR}/Math/Matrix4x4.hpp
    ${POMDOG_INC_DIR}/Math/Plane.hpp
    ${POMDOG_SRC_DIR}/Math/Plane.cpp
    ${POMDOG_INC_DIR}/Math/PlaneIntersectionType.hpp
    ${POMDOG_INC_DIR}/Math/Point2D.hpp
    ${POMDOG_INC_DIR}/Math/Point3D.hpp
    ${POMDOG_INC_DIR}/Math/Quaternion.hpp
    ${POMDOG_INC_DIR}/Math/Radian.hpp
    ${POMDOG_INC_DIR}/Math/Ray.hpp
    ${POMDOG_SRC_DIR}/Math/Ray.cpp
    ${POMDOG_INC_DIR}/Math/Rectangle.hpp
    ${POMDOG_SRC_DIR}/Math/Rectangle.cpp
    ${POMDOG_INC_DIR}/Math/Vector2.hpp
    ${POMDOG_INC_DIR}/Math/Vector3.hpp
    ${POMDOG_INC_DIR}/Math/Vector4.hpp
    ${POMDOG_INC_DIR}/Math/Detail/Coordinate2D.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/Coordinate2D.cpp
    ${POMDOG_INC_DIR}/Math/Detail/Coordinate3D.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/Coordinate3D.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointMatrix2x2.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointMatrix2x2.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointMatrix3x2.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointMatrix3x2.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointMatrix3x3.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointMatrix3x3.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointMatrix4x4.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointMatrix4x4.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointQuaternion.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointQuaternion.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointVector2.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointVector2.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointVector3.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointVector3.cpp
    ${POMDOG_INC_DIR}/Math/Detail/FloatingPointVector4.hpp
    ${POMDOG_SRC_DIR}/Math/Detail/FloatingPointVector4.cpp
    ${POMDOG_INC_DIR}/Math/Detail/TaggedArithmetic.hpp
    ${POMDOG_INC_DIR}/Math/Detail/TypeTraits.hpp
)
