os: osx
osx_image: xcode9.2
language: cpp

compiler:
  - clang

install:
  - git submodule update --init --depth 1

script:
  - xcodebuild -project build/PomdogTest.xcodeproj clean
  - xcodebuild -project build/PomdogTest.xcodeproj
  - xcodebuild -project examples/QuickStart/Builds/QuickStart.xcodeproj clean
  - xcodebuild -project examples/QuickStart/Builds/QuickStart.xcodeproj
  - build/build/Release/PomdogUnitTest
  - mkdir build.cmake && cd build.cmake
  - cmake -G Xcode ..
  - cd ..
  - xcodebuild -project build.cmake/Pomdog.xcodeproj
  - build.cmake/build/PomdogTest/Debug/PomdogTest

notifications:
  email: false
