os: osx
osx_image: xcode10
language: cpp

compiler:
  - clang

install:
  - git submodule update --init --depth 1

script:
  - xcodebuild -project build/PomdogTest.xcodeproj clean
  - xcodebuild -project build/PomdogTest.xcodeproj
  - xcodebuild -project examples/QuickStart/Builds/QuickStart.xcodeproj clean
  - xcodebuild -project examples/QuickStart/Builds/QuickStart.xcodeproj
  - build/build/Release/PomdogUnitTest
  - mkdir build.cmake && cd build.cmake
  - cmake -G Xcode ..
  - xcodebuild -project Pomdog.xcodeproj -configuration Debug
  - xcodebuild -project Pomdog.xcodeproj -configuration Release
  - test/Debug/PomdogTest
  - test/Release/PomdogTest
  - cd ..

notifications:
  email: false
