cmake_minimum_required(VERSION 3.31)
project(pomdog)

option(POMDOG_BUILD_EXAMPLES "Build example applications" ${PROJECT_IS_TOP_LEVEL})
option(POMDOG_BUILD_TESTS "Build engine unit tests" ${PROJECT_IS_TOP_LEVEL})
option(POMDOG_BUILD_QUICKSTART "Build the quickstart example" ${POMDOG_BUILD_EXAMPLES})
option(POMDOG_BUILD_PONG "Build the pong example" ${POMDOG_BUILD_EXAMPLES})
option(POMDOG_BUILD_FEATURE_SHOWCASE "Build the feature showcase" ${POMDOG_BUILD_EXAMPLES})

add_subdirectory(cmake/pomdog)
add_subdirectory(cmake/pomdog_app_settings)
if(POMDOG_BUILD_EXAMPLES)
    if(POMDOG_BUILD_FEATURE_SHOWCASE)
        add_subdirectory(examples/feature_showcase)
    endif()
    if(POMDOG_BUILD_PONG)
        add_subdirectory(examples/pong)
    endif()
    if(POMDOG_BUILD_QUICKSTART)
        add_subdirectory(examples/quickstart)
    endif()
endif()
if(POMDOG_BUILD_TESTS)
    add_subdirectory(tests)
endif()
