[[sound_clip]]
in_file = "sounds/ambient_lakeside.wav"
out_file = "sounds/ambient_lakeside_oneshot.wav"
in_format = "wav"
out_format = "wav"
wav_options = {channels = 1, sample_rate = 22050, bit_depth = 16}

[[sound_clip]]
in_file = "sounds/ambient_lakeside.wav"
out_file = "sounds/ambient_lakeside_wav.wav"
in_format = "wav"
out_format = "wav"
wav_options = {channels = 1, sample_rate = 44100, bit_depth = 16}
loop = {trim_start = true, seconds = 2.0, align_samples = 4096}

[[sound_clip]]
in_file = "sounds/ambient_lakeside.wav"
out_file = "sounds/ambient_lakeside_vorbis.ogg"
in_format = "wav"
out_format = "vorbis"
vorbis_options = {channels = 1, sample_rate = 44100, bit_rate = 128}
loop = {trim_start = true, seconds = 2.0, align_samples = 4096}

[[tileset_from_spine_atlas]]
in_atlas = "skeletal2d/Ghost/Ghost.atlas"
in_image = "skeletal2d/Ghost/Ghost.png"
out_tileset = "skeletal2d/Ghost/Ghost.tileset"
out_texture = "skeletal2d/Ghost/Ghost.png"
premultiplied_alpha = true

[[tileset_from_spine_atlas]]
in_atlas = "skeletal2d/MaidChan/skeleton.atlas"
in_image = "skeletal2d/MaidChan/skeleton.png"
out_tileset = "skeletal2d/MaidChan/skeleton.tileset"
out_texture = "skeletal2d/MaidChan/skeleton.png"
premultiplied_alpha = true

[[tileset_from_spine_atlas]]
in_atlas = "skeletal2d/MaidChan2/skeleton.atlas"
in_image = "skeletal2d/MaidChan2/skeleton.png"
out_tileset = "skeletal2d/MaidChan2/skeleton.tileset"
out_texture = "skeletal2d/MaidChan2/skeleton.png"
premultiplied_alpha = true

[[tileset_from_spine_atlas]]
in_atlas = "skeletal2d/MaidGun/MaidGun.atlas"
in_image = "skeletal2d/MaidGun/MaidGun.png"
out_tileset = "skeletal2d/MaidGun/MaidGun.tileset"
out_texture = "skeletal2d/MaidGun/MaidGun.png"
premultiplied_alpha = true

[[tileset_from_piskel]]
out_tileset = "pixelart/girl_with_gun.tileset"
out_texture = "pixelart/girl_with_gun.png"
in_recipe = [
    "pixelart/tileset_base.toml",
    "pixelart/tileset_girl_with_gun.toml",
]

[[tileset_from_piskel]]
out_tileset = "pixelart/misc.tileset"
out_texture = "pixelart/misc.png"
in_recipe = [
    "pixelart/tileset_base.toml",
    "pixelart/tileset_gothapron.toml",
    "pixelart/tileset_misc.toml",
]

[[tileset_from_pngs]]
recipe = "textures/tileset_spritesheet.toml"
out_tileset = "textures/spritesheet.tileset"
out_texture = "textures/spritesheet.png"
