// Copyright (c) 2013-2016 mogemimi. Distributed under the MIT license.

char const* Builtin_GLSL_SpriteBatch_VS =
"#version 330\n"
"layout(location=0)in vec4 PositionTextureCoord;\n"
"layout(location=1)in vec4 Translation;\n"
"layout(location=2)in vec4 SourceRect;\n"
"layout(location=3)in vec4 OriginRotationDepth;\n"
"layout(location=4)in vec4 Color;\n"
"out VertexData{\n"
"vec4 Color;\n"
"vec2 TextureCoord;}Out;\n"
"uniform SpriteBatchConstants{\n"
"mat4x4 ViewProjection;};\n"
"uniform TextureConstants{\n"
"vec4 InverseTextureSize;};\n"
"void main(){\n"
"mat3x3 scaling=mat3x3(\n"
"vec3(Translation.z*SourceRect.z,0.0,0.0),\n"
"vec3(0.0,Translation.w*SourceRect.w,0.0),\n"
"vec3(0.0,0.0,1.0));\n"
"float cosRotation=cos(OriginRotationDepth.z);\n"
"float sinRotation=sin(OriginRotationDepth.z);\n"
"mat3x3 rotate=mat3x3(\n"
"vec3(cosRotation,sinRotation,0.0),\n"
"vec3(-sinRotation,cosRotation,0.0),\n"
"vec3(0.0f,0.0f,1.0));\n"
"mat3x3 translate=mat3x3(\n"
"vec3(1.0,0.0,0.0),\n"
"vec3(0.0,1.0,0.0),\n"
"vec3(Translation.xy,1.0));\n"
"mat3x3 transform=translate*(rotate*scaling);\n"
"vec3 position=(transform*vec3(PositionTextureCoord.xy-OriginRotationDepth.xy,1.0));\n"
"vec4 finalPosition=vec4(position.xy,0.0,1.0)*ViewProjection;\n"
"gl_Position=vec4(finalPosition.xy,OriginRotationDepth.w,1.0);\n"
"Out.TextureCoord=(PositionTextureCoord.zw*SourceRect.zw+SourceRect.xy)*InverseTextureSize.xy;\n"
"Out.Color=Color;}\n";
