## simple_effect

[[compile_vs]]
name = "simple_effect_vs"
source = "simple_effect.slang"
entrypoint = "simple_effect_vs"

[[compile_ps]]
name = "simple_effect_ps"
source = "simple_effect.slang"
entrypoint = "simple_effect_ps"
vsout = "simple_effect_vs"

## links (validation only)

[[link]]
name = "simple_effect"
vs = "simple_effect_vs"
ps = "simple_effect_ps"
