[[group]]
paths = [
    "fonts/NotoSans-Bold.ttf",
    "fonts/NotoSans-Regular.ttf",
    "fonts/Roboto-Black.ttf",
    "glb/f15.glb",
    "particles/fire2d.json",
    "particles/fire3d_box.json",
    "particles/fire3d_cone.json",
    "particles/fire3d_hemisphere.json",
    "particles/fire3d_sphere.json",
    "particles/water2d.json",
    "particles/water3d.json",
    "pixelart/girl_with_gun.tileset",
    "pixelart/girl_with_gun.png",
    "pixelart/misc.tileset",
    "pixelart/misc.png",
    "skeletal2d/Ghost/AnimationGraph.json",
    "skeletal2d/Ghost/Ghost.json",
    "skeletal2d/Ghost/Ghost.png",
    "skeletal2d/Ghost/Ghost.tileset",
    "skeletal2d/MaidChan/skeleton.json",
    "skeletal2d/MaidChan/skeleton.png",
    "skeletal2d/MaidChan/skeleton.tileset",
    "skeletal2d/MaidChan2/skeleton.json",
    "skeletal2d/MaidChan2/skeleton.png",
    "skeletal2d/MaidChan2/skeleton.tileset",
    "skeletal2d/MaidGun/AnimationGraph.json",
    "skeletal2d/MaidGun/MaidGun.json",
    "skeletal2d/MaidGun/MaidGun.png",
    "skeletal2d/MaidGun/MaidGun.tileset",
    "sounds/ambient_lakeside_oneshot.wav",
    "sounds/ambient_lakeside_vorbis.ogg",
    "sounds/ambient_lakeside_wav.wav",
    "sounds/pong1.wav",
    "sounds/synth.ogg",
    "svg/ios-arrow-back.svg",
    "svg/ios-arrow-down.svg",
    "svg/ios-arrow-forward.svg",
    "svg/ios-arrow-up.svg",
    "svg/ios-search.svg",
    "svg/ios-square-outline.svg",
    "svg/ios-square.svg",
    "svg/ios-volume-high.svg",
    "svg/ios-volume-low.svg",
    "svg/ios-volume-mute.svg",
    "svg/ios-volume-off.svg",
    "svg/md-add.svg",
    "svg/md-arrow-back.svg",
    "svg/md-arrow-down.svg",
    "svg/md-arrow-dropdown.svg",
    "svg/md-arrow-dropleft.svg",
    "svg/md-arrow-dropright.svg",
    "svg/md-arrow-dropup.svg",
    "svg/md-arrow-forward.svg",
    "svg/md-arrow-up.svg",
    "svg/md-backspace.svg",
    "svg/md-build.svg",
    "svg/md-camera.svg",
    "svg/md-checkmark.svg",
    "svg/md-close-circle-outline.svg",
    "svg/md-close-circle.svg",
    "svg/md-close.svg",
    "svg/md-construct.svg",
    "svg/md-copy.svg",
    "svg/md-document.svg",
    "svg/md-download.svg",
    "svg/md-expand.svg",
    "svg/md-eye-off.svg",
    "svg/md-eye.svg",
    "svg/md-lock.svg",
    "svg/md-refresh.svg",
    "svg/md-star-outline.svg",
    "svg/md-star.svg",
    "textures/particle_lightning.png",
    "textures/particle_smoke.png",
    "textures/pomdog-dxt1.dds",
    "textures/pomdog-dxt5.dds",
    "textures/pomdog-p1.pbm",
    "textures/pomdog-p2.pgm",
    "textures/pomdog-p3.ppm",
    "textures/pomdog-p4.pbm",
    "textures/pomdog-p5.pgm",
    "textures/pomdog-p6.ppm",
    "textures/pomdog.png",
    "textures/spritesheet.tileset",
    "textures/spritesheet.png",
    "voxel_models/maidchan.vox",
]
