width = 256
height = 256
per_tile_spacing = 0
tile_border_size = 1
tight_packing = true
premultiplied_alpha = true

tiles = [
    # NOTE: `girl_with_gun.piskel` has 88 frames of animation.
    {name = "girl_with_gun_1", source = "girl_with_gun.piskel", index = 1},
    {name = "girl_with_gun_2", source = "girl_with_gun.piskel", index = 2},
    {name = "girl_with_gun_3", source = "girl_with_gun.piskel", index = 3},
    {name = "girl_with_gun_4", source = "girl_with_gun.piskel", index = 4},
    {name = "girl_with_gun_5", source = "girl_with_gun.piskel", index = 5},
    {name = "girl_with_gun_6", source = "girl_with_gun.piskel", index = 6},
    {name = "girl_with_gun_7", source = "girl_with_gun.piskel", index = 7},
    {name = "girl_with_gun_8", source = "girl_with_gun.piskel", index = 8},
    {name = "girl_with_gun_9", source = "girl_with_gun.piskel", index = 9},
    {name = "girl_with_gun_10", source = "girl_with_gun.piskel", index = 10},
    {name = "girl_with_gun_11", source = "girl_with_gun.piskel", index = 11},
    {name = "girl_with_gun_12", source = "girl_with_gun.piskel", index = 12},
    {name = "girl_with_gun_13", source = "girl_with_gun.piskel", index = 13},
    {name = "girl_with_gun_14", source = "girl_with_gun.piskel", index = 14},
    {name = "girl_with_gun_15", source = "girl_with_gun.piskel", index = 15},
    {name = "girl_with_gun_16", source = "girl_with_gun.piskel", index = 16},
    {name = "girl_with_gun_17", source = "girl_with_gun.piskel", index = 17},
    {name = "girl_with_gun_18", source = "girl_with_gun.piskel", index = 18},
    {name = "girl_with_gun_19", source = "girl_with_gun.piskel", index = 19},
    {name = "girl_with_gun_20", source = "girl_with_gun.piskel", index = 20},
    {name = "girl_with_gun_21", source = "girl_with_gun.piskel", index = 21},
    {name = "girl_with_gun_22", source = "girl_with_gun.piskel", index = 22},
    {name = "girl_with_gun_23", source = "girl_with_gun.piskel", index = 23},
    {name = "girl_with_gun_24", source = "girl_with_gun.piskel", index = 24},
    {name = "girl_with_gun_25", source = "girl_with_gun.piskel", index = 25},
    {name = "girl_with_gun_26", source = "girl_with_gun.piskel", index = 26},
    {name = "girl_with_gun_27", source = "girl_with_gun.piskel", index = 27},
    {name = "girl_with_gun_28", source = "girl_with_gun.piskel", index = 28},
    {name = "girl_with_gun_29", source = "girl_with_gun.piskel", index = 29},
    {name = "girl_with_gun_30", source = "girl_with_gun.piskel", index = 30},
    {name = "girl_with_gun_31", source = "girl_with_gun.piskel", index = 31},
    {name = "girl_with_gun_32", source = "girl_with_gun.piskel", index = 32},
    {name = "girl_with_gun_33", source = "girl_with_gun.piskel", index = 33},
    {name = "girl_with_gun_34", source = "girl_with_gun.piskel", index = 34},
    {name = "girl_with_gun_35", source = "girl_with_gun.piskel", index = 35},
    {name = "girl_with_gun_36", source = "girl_with_gun.piskel", index = 36},
    {name = "girl_with_gun_37", source = "girl_with_gun.piskel", index = 37},
    {name = "girl_with_gun_38", source = "girl_with_gun.piskel", index = 38},
    {name = "girl_with_gun_39", source = "girl_with_gun.piskel", index = 39},
    {name = "girl_with_gun_40", source = "girl_with_gun.piskel", index = 40},
    {name = "girl_with_gun_41", source = "girl_with_gun.piskel", index = 41},
    {name = "girl_with_gun_42", source = "girl_with_gun.piskel", index = 42},
    {name = "girl_with_gun_43", source = "girl_with_gun.piskel", index = 43},
    {name = "girl_with_gun_44", source = "girl_with_gun.piskel", index = 44},
    {name = "girl_with_gun_45", source = "girl_with_gun.piskel", index = 45},
    {name = "girl_with_gun_46", source = "girl_with_gun.piskel", index = 46},
    {name = "girl_with_gun_47", source = "girl_with_gun.piskel", index = 47},
    {name = "girl_with_gun_48", source = "girl_with_gun.piskel", index = 48},
    {name = "girl_with_gun_49", source = "girl_with_gun.piskel", index = 49},
    {name = "girl_with_gun_50", source = "girl_with_gun.piskel", index = 50},
    {name = "girl_with_gun_51", source = "girl_with_gun.piskel", index = 51},
    {name = "girl_with_gun_52", source = "girl_with_gun.piskel", index = 52},
    {name = "girl_with_gun_53", source = "girl_with_gun.piskel", index = 53},
    {name = "girl_with_gun_54", source = "girl_with_gun.piskel", index = 54},
    {name = "girl_with_gun_55", source = "girl_with_gun.piskel", index = 55},
    {name = "girl_with_gun_56", source = "girl_with_gun.piskel", index = 56},
    {name = "girl_with_gun_57", source = "girl_with_gun.piskel", index = 57},
    {name = "girl_with_gun_58", source = "girl_with_gun.piskel", index = 58},
    {name = "girl_with_gun_59", source = "girl_with_gun.piskel", index = 59},
    {name = "girl_with_gun_60", source = "girl_with_gun.piskel", index = 60},
    {name = "girl_with_gun_61", source = "girl_with_gun.piskel", index = 61},
    {name = "girl_with_gun_62", source = "girl_with_gun.piskel", index = 62},
    {name = "girl_with_gun_63", source = "girl_with_gun.piskel", index = 63},
    {name = "girl_with_gun_64", source = "girl_with_gun.piskel", index = 64},
    {name = "girl_with_gun_65", source = "girl_with_gun.piskel", index = 65},
    {name = "girl_with_gun_66", source = "girl_with_gun.piskel", index = 66},
    {name = "girl_with_gun_67", source = "girl_with_gun.piskel", index = 67},
    {name = "girl_with_gun_68", source = "girl_with_gun.piskel", index = 68},
    {name = "girl_with_gun_69", source = "girl_with_gun.piskel", index = 69},
    {name = "girl_with_gun_70", source = "girl_with_gun.piskel", index = 70},
    {name = "girl_with_gun_71", source = "girl_with_gun.piskel", index = 71},
    {name = "girl_with_gun_72", source = "girl_with_gun.piskel", index = 72},
    {name = "girl_with_gun_73", source = "girl_with_gun.piskel", index = 73},
    {name = "girl_with_gun_74", source = "girl_with_gun.piskel", index = 74},
    {name = "girl_with_gun_75", source = "girl_with_gun.piskel", index = 75},
    {name = "girl_with_gun_76", source = "girl_with_gun.piskel", index = 76},
    {name = "girl_with_gun_77", source = "girl_with_gun.piskel", index = 77},
    {name = "girl_with_gun_78", source = "girl_with_gun.piskel", index = 78},
    {name = "girl_with_gun_79", source = "girl_with_gun.piskel", index = 79},
    {name = "girl_with_gun_80", source = "girl_with_gun.piskel", index = 80},
    {name = "girl_with_gun_81", source = "girl_with_gun.piskel", index = 81},
    {name = "girl_with_gun_82", source = "girl_with_gun.piskel", index = 82},
    {name = "girl_with_gun_83", source = "girl_with_gun.piskel", index = 83},
    {name = "girl_with_gun_84", source = "girl_with_gun.piskel", index = 84},
    {name = "girl_with_gun_85", source = "girl_with_gun.piskel", index = 85},
    {name = "girl_with_gun_86", source = "girl_with_gun.piskel", index = 86},
    {name = "girl_with_gun_87", source = "girl_with_gun.piskel", index = 87},
    {name = "girl_with_gun_88", source = "girl_with_gun.piskel", index = 88},
]
