name: "Build on Ubuntu"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mogemimi/gamedev-ubuntu
    strategy:
      matrix:
        build_config: [Debug, Release]
        cmake_flags:
          - cxx_flags: -stdlib=libc++
            linker_flags: -stdlib=libc++ -lc++abi
          - cxx_flags: -stdlib=libstdc++
            linker_flags: -stdlib=libstdc++
    steps:
      - name: Check out repositry
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 50 # FIXME: for giflib submodule
      - name: Generate Ninja files
        run: |
          cmake -Bbuild.cmake -H. -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_FLAGS="${{ matrix.cmake_flags.cxx_flags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.cmake_flags.linker_flags }}"
      - name: Build
        run: ninja -C build.cmake
      - name: Run test
        run: ./build.cmake/test/PomdogTest
