name: "Build on ArchLinux"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mogemimi/gamedev-archlinux
    strategy:
      matrix:
        build_config: [Debug, Release]
    steps:
      - name: Check out repositry
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 50 # FIXME: for giflib submodule
      - name: Generate Ninja files
        run: |
          cmake -Bbuild.cmake -H. -G Ninja \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_config }}
      - name: Build
        run: ninja -C build.cmake
      - name: Run test
        run: ./build.cmake/test/PomdogTest
